name: Mac OS
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Compile C-based resolver test
      run: |
        gcc -o getaddrinfo -O2 getaddrinfo.c
    - name: Run C-based resolver test
      run: |
        ./getaddrinfo
